### ISSUE TITLE
Feature request: allow to modify max file size

### ISSUE THREAD

**Issue by countless-integers** [nilportugues/sitemap-component#41]
I'd be really cool to be able to set max file size for sitemap spanning over multiple files. [According to google max file size is 50MB](https://support.google.com/webmasters/answer/183668?hl=en), and this is what is [hardcoded right now](https://github.com/nilportugues/sitemap-component/blob/f23b08d3226c5607318ea2f07eab36aaa4c4d8a6/src/AbstractSitemap.php#L52). According to [sitemap.org](http://www.sitemaps.org/protocol.html#otherformats) it's 10MB. Either way it would be nice to let the user decide what the size should be. A simple setter might do, what do you think?

**Comment by nilopc** [comment]
Definitely could be done and makes perfect sense.

I'm thinking of making it the fourth parameter in the __construct() method for all classes inheriting from https://github.com/nilportugues/sitemap-component/blob/master/src/AbstractSitemap.php.

Count on it to be done in the following days... or provide a PR before. :)

Once done I'll create a new release 3.0.2

**Comment by nilopc** [comment]
@countless-integers there you go https://github.com/nilportugues/sitemap-component/releases/tag/3.0.3

**Comment by countless-integers** [comment]
Looks awesome. I'll try it out next week. Thanks!
